# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 605)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/main_icon.icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.start = QtWidgets.QWidget()
        self.start.setObjectName("start")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.start)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.start)
        self.label_3.setMaximumSize(QtCore.QSize(30, 30))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/icons/inventario.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.label_4 = QtWidgets.QLabel(self.start)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.but_add_item = QtWidgets.QPushButton(self.start)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/mas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_add_item.setIcon(icon1)
        self.but_add_item.setObjectName("but_add_item")
        self.verticalLayout.addWidget(self.but_add_item)
        self.pushButton_4 = QtWidgets.QPushButton(self.start)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/borrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.but_new_order = QtWidgets.QPushButton(self.start)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_new_order.sizePolicy().hasHeightForWidth())
        self.but_new_order.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/etiqueta-del-precio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_new_order.setIcon(icon3)
        self.but_new_order.setIconSize(QtCore.QSize(30, 30))
        self.but_new_order.setObjectName("but_new_order")
        self.horizontalLayout_3.addWidget(self.but_new_order)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.start)
        self.new_order = QtWidgets.QWidget()
        self.new_order.setObjectName("new_order")
        self.line = QtWidgets.QFrame(self.new_order)
        self.line.setGeometry(QtCore.QRect(9, 43, 16, 16))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.but_return_to_start = QtWidgets.QPushButton(self.new_order)
        self.but_return_to_start.setGeometry(QtCore.QRect(733, 9, 40, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_return_to_start.sizePolicy().hasHeightForWidth())
        self.but_return_to_start.setSizePolicy(sizePolicy)
        self.but_return_to_start.setMinimumSize(QtCore.QSize(25, 25))
        self.but_return_to_start.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/casa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_return_to_start.setIcon(icon4)
        self.but_return_to_start.setObjectName("but_return_to_start")
        self.formLayoutWidget = QtWidgets.QWidget(self.new_order)
        self.formLayoutWidget.setGeometry(QtCore.QRect(350, 290, 192, 157))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.impresoraLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.impresoraLabel.setObjectName("impresoraLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.impresoraLabel)
        self.prippComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.prippComboBox.setObjectName("prippComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.prippComboBox)
        self.materialLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.materialLabel.setObjectName("materialLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.materialLabel)
        self.materialComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.materialComboBox.setObjectName("materialComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.materialComboBox)
        self.materialLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.materialLabel_2.setObjectName("materialLabel_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.materialLabel_2)
        self.materialComboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.materialComboBox_2.setObjectName("materialComboBox_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.materialComboBox_2)
        self.materialWeigthLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.materialWeigthLabel.setObjectName("materialWeigthLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.materialWeigthLabel)
        self.materialWeigthComboBox = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.materialWeigthComboBox.setClearButtonEnabled(True)
        self.materialWeigthComboBox.setObjectName("materialWeigthComboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.materialWeigthComboBox)
        self.customerLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.customerLabel.setObjectName("customerLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.customerLabel)
        self.toolButton = QtWidgets.QToolButton(self.formLayoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.toolButton)
        self.label = QtWidgets.QLabel(self.new_order)
        self.label.setGeometry(QtCore.QRect(10, 50, 129, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.new_order)
        self.edit_inventory = QtWidgets.QWidget()
        self.edit_inventory.setObjectName("edit_inventory")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.edit_inventory)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listWidget_SelectNewItem = QtWidgets.QListWidget(self.edit_inventory)
        self.listWidget_SelectNewItem.setLineWidth(1)
        self.listWidget_SelectNewItem.setObjectName("listWidget_SelectNewItem")
        self.horizontalLayout_5.addWidget(self.listWidget_SelectNewItem)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.edit_inventory)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.blank = QtWidgets.QWidget()
        self.blank.setObjectName("blank")
        self.stackedWidget_2.addWidget(self.blank)
        self.printer = QtWidgets.QWidget()
        self.printer.setObjectName("printer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.printer)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.nameLabel = QtWidgets.QLabel(self.printer)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.printer)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.costoDeUsoLabel = QtWidgets.QLabel(self.printer)
        self.costoDeUsoLabel.setObjectName("costoDeUsoLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.costoDeUsoLabel)
        self.spinBox = QtWidgets.QSpinBox(self.printer)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.gridLayout_3.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.printer)
        self.filament = QtWidgets.QWidget()
        self.filament.setObjectName("filament")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.filament)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.nameLabel_2 = QtWidgets.QLabel(self.filament)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel_2)
        self.nameLineEdit_2 = QtWidgets.QLineEdit(self.filament)
        self.nameLineEdit_2.setObjectName("nameLineEdit_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit_2)
        self.materialLabel_3 = QtWidgets.QLabel(self.filament)
        self.materialLabel_3.setObjectName("materialLabel_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.materialLabel_3)
        self.materialComboBox_3 = QtWidgets.QComboBox(self.filament)
        self.materialComboBox_3.setObjectName("materialComboBox_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.materialComboBox_3)
        self.costoDelCarreteLabel = QtWidgets.QLabel(self.filament)
        self.costoDelCarreteLabel.setObjectName("costoDelCarreteLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.costoDelCarreteLabel)
        self.costoDelCarreteSpinBox = QtWidgets.QSpinBox(self.filament)
        self.costoDelCarreteSpinBox.setObjectName("costoDelCarreteSpinBox")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.costoDelCarreteSpinBox)
        self.gramosDelCarreteLabel = QtWidgets.QLabel(self.filament)
        self.gramosDelCarreteLabel.setObjectName("gramosDelCarreteLabel")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gramosDelCarreteLabel)
        self.spinBox_2 = QtWidgets.QSpinBox(self.filament)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.gramosRestantesLabel = QtWidgets.QLabel(self.filament)
        self.gramosRestantesLabel.setObjectName("gramosRestantesLabel")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gramosRestantesLabel)
        self.spinBox_3 = QtWidgets.QSpinBox(self.filament)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.gridLayout_6.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.filament)
        self.customer = QtWidgets.QWidget()
        self.customer.setObjectName("customer")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.customer)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.nameLabel_3 = QtWidgets.QLabel(self.customer)
        self.nameLabel_3.setObjectName("nameLabel_3")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel_3)
        self.nameLineEdit_3 = QtWidgets.QLineEdit(self.customer)
        self.nameLineEdit_3.setObjectName("nameLineEdit_3")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit_3)
        self.lastNameLabel = QtWidgets.QLabel(self.customer)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lastNameLabel)
        self.lastNameLineEdit = QtWidgets.QLineEdit(self.customer)
        self.lastNameLineEdit.setObjectName("lastNameLineEdit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lastNameLineEdit)
        self.phoneNumberLabel = QtWidgets.QLabel(self.customer)
        self.phoneNumberLabel.setObjectName("phoneNumberLabel")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.phoneNumberLabel)
        self.phoneNumberLineEdit = QtWidgets.QLineEdit(self.customer)
        self.phoneNumberLineEdit.setObjectName("phoneNumberLineEdit")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.phoneNumberLineEdit)
        self.gridLayout_7.addLayout(self.formLayout_5, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.customer)
        self.horizontalLayout_5.addWidget(self.stackedWidget_2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.edit_inventory)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 2, 1, 1)
        self.but_add = QtWidgets.QPushButton(self.edit_inventory)
        self.but_add.setObjectName("but_add")
        self.gridLayout.addWidget(self.but_add, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.but_return_to_start_2 = QtWidgets.QPushButton(self.edit_inventory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_return_to_start_2.sizePolicy().hasHeightForWidth())
        self.but_return_to_start_2.setSizePolicy(sizePolicy)
        self.but_return_to_start_2.setMinimumSize(QtCore.QSize(25, 25))
        self.but_return_to_start_2.setText("")
        self.but_return_to_start_2.setIcon(icon4)
        self.but_return_to_start_2.setObjectName("but_return_to_start_2")
        self.gridLayout_5.addWidget(self.but_return_to_start_2, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.edit_inventory)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.edit_inventory)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.stackedWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3DPricing"))
        self.label_4.setText(_translate("MainWindow", "Inventario"))
        self.but_add_item.setText(_translate("MainWindow", "Añadir item"))
        self.pushButton_4.setText(_translate("MainWindow", "Eliminar item"))
        self.but_new_order.setText(_translate("MainWindow", "Nueva orden"))
        self.but_return_to_start.setToolTip(_translate("MainWindow", "<html><head/><body><p>Volver al inicio</p></body></html>"))
        self.impresoraLabel.setText(_translate("MainWindow", "Impresora"))
        self.materialLabel.setText(_translate("MainWindow", "Material"))
        self.materialLabel_2.setText(_translate("MainWindow", "Material"))
        self.materialWeigthLabel.setText(_translate("MainWindow", "Gramos de material"))
        self.customerLabel.setText(_translate("MainWindow", "Cliente"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.nameLabel.setText(_translate("MainWindow", "Nombre"))
        self.costoDeUsoLabel.setText(_translate("MainWindow", "Costo de uso"))
        self.spinBox.setSuffix(_translate("MainWindow", " $/hora"))
        self.nameLabel_2.setText(_translate("MainWindow", "Nombre"))
        self.materialLabel_3.setText(_translate("MainWindow", "Material"))
        self.costoDelCarreteLabel.setText(_translate("MainWindow", "Costo del carrete"))
        self.gramosDelCarreteLabel.setText(_translate("MainWindow", "Gramos del carrete"))
        self.gramosRestantesLabel.setText(_translate("MainWindow", "Gramos restantes"))
        self.nameLabel_3.setText(_translate("MainWindow", "Nombre"))
        self.lastNameLabel.setText(_translate("MainWindow", "Apellido"))
        self.phoneNumberLabel.setText(_translate("MainWindow", "Número telefónico"))
        self.pushButton.setText(_translate("MainWindow", "Limpiar campos"))
        self.but_add.setText(_translate("MainWindow", "Añadir"))
        self.but_return_to_start_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Volver al inicio</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Añadir item"))
import resources_rc
