# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 650)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/main_icon.icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.start = QtWidgets.QWidget()
        self.start.setObjectName("start")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.start)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.start)
        self.label_3.setMaximumSize(QtCore.QSize(30, 30))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/icons/inventario.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.label_4 = QtWidgets.QLabel(self.start)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.but_add_item = QtWidgets.QPushButton(self.start)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/mas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_add_item.setIcon(icon1)
        self.but_add_item.setObjectName("but_add_item")
        self.verticalLayout.addWidget(self.but_add_item)
        self.pushButton_4 = QtWidgets.QPushButton(self.start)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/borrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.but_new_order = QtWidgets.QPushButton(self.start)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_new_order.sizePolicy().hasHeightForWidth())
        self.but_new_order.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/etiqueta-del-precio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_new_order.setIcon(icon3)
        self.but_new_order.setIconSize(QtCore.QSize(30, 30))
        self.but_new_order.setObjectName("but_new_order")
        self.horizontalLayout_3.addWidget(self.but_new_order)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.start)
        self.new_order = QtWidgets.QWidget()
        self.new_order.setObjectName("new_order")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.new_order)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, 61, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.new_order)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem5)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.impresoraLabel = QtWidgets.QLabel(self.new_order)
        self.impresoraLabel.setObjectName("impresoraLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.impresoraLabel)
        self.prippComboBox = QtWidgets.QComboBox(self.new_order)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prippComboBox.sizePolicy().hasHeightForWidth())
        self.prippComboBox.setSizePolicy(sizePolicy)
        self.prippComboBox.setObjectName("prippComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.prippComboBox)
        self.materialLabel = QtWidgets.QLabel(self.new_order)
        self.materialLabel.setObjectName("materialLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.materialLabel)
        self.materialComboBox = QtWidgets.QComboBox(self.new_order)
        self.materialComboBox.setObjectName("materialComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.materialComboBox)
        self.materialLabel_2 = QtWidgets.QLabel(self.new_order)
        self.materialLabel_2.setObjectName("materialLabel_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.materialLabel_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox_5 = QtWidgets.QSpinBox(self.new_order)
        self.spinBox_5.setMaximum(500)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout.addWidget(self.spinBox_5)
        self.spinBox_4 = QtWidgets.QSpinBox(self.new_order)
        self.spinBox_4.setMaximum(59)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout.addWidget(self.spinBox_4)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.materialWeigthLabel = QtWidgets.QLabel(self.new_order)
        self.materialWeigthLabel.setObjectName("materialWeigthLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.materialWeigthLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.spinBox_6 = QtWidgets.QSpinBox(self.new_order)
        self.spinBox_6.setMaximum(9999)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_4.addWidget(self.spinBox_6)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.customerLabel = QtWidgets.QLabel(self.new_order)
        self.customerLabel.setObjectName("customerLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.customerLabel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.customers_comboBox = QtWidgets.QComboBox(self.new_order)
        self.customers_comboBox.setObjectName("customers_comboBox")
        self.horizontalLayout_6.addWidget(self.customers_comboBox)
        self.customers_toolButton = QtWidgets.QToolButton(self.new_order)
        self.customers_toolButton.setObjectName("customers_toolButton")
        self.horizontalLayout_6.addWidget(self.customers_toolButton)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.carreteLabel = QtWidgets.QLabel(self.new_order)
        self.carreteLabel.setObjectName("carreteLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.carreteLabel)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.filament_comboBox = QtWidgets.QComboBox(self.new_order)
        self.filament_comboBox.setObjectName("filament_comboBox")
        self.horizontalLayout_7.addWidget(self.filament_comboBox)
        self.toolButton = QtWidgets.QToolButton(self.new_order)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_7.addWidget(self.toolButton)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.line = QtWidgets.QFrame(self.new_order)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.removerLaImpresiNLabel = QtWidgets.QLabel(self.new_order)
        self.removerLaImpresiNLabel.setObjectName("removerLaImpresiNLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.removerLaImpresiNLabel)
        self.slicing_time_SpinBox = QtWidgets.QSpinBox(self.new_order)
        self.slicing_time_SpinBox.setMaximum(999)
        self.slicing_time_SpinBox.setObjectName("slicing_time_SpinBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.slicing_time_SpinBox)
        self.iniciarImpresiNLabel = QtWidgets.QLabel(self.new_order)
        self.iniciarImpresiNLabel.setObjectName("iniciarImpresiNLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.iniciarImpresiNLabel)
        self.iniciarImpresiNSpinBox = QtWidgets.QSpinBox(self.new_order)
        self.iniciarImpresiNSpinBox.setMaximum(999)
        self.iniciarImpresiNSpinBox.setObjectName("iniciarImpresiNSpinBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.iniciarImpresiNSpinBox)
        self.cambioDeFilamentoYHerramientasLabel = QtWidgets.QLabel(self.new_order)
        self.cambioDeFilamentoYHerramientasLabel.setObjectName("cambioDeFilamentoYHerramientasLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cambioDeFilamentoYHerramientasLabel)
        self.cambioDeFilamentoYHerramientasSpinBox = QtWidgets.QSpinBox(self.new_order)
        self.cambioDeFilamentoYHerramientasSpinBox.setMaximum(999)
        self.cambioDeFilamentoYHerramientasSpinBox.setObjectName("cambioDeFilamentoYHerramientasSpinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cambioDeFilamentoYHerramientasSpinBox)
        self.removerImpresiNLabel = QtWidgets.QLabel(self.new_order)
        self.removerImpresiNLabel.setObjectName("removerImpresiNLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.removerImpresiNLabel)
        self.removerImpresiNSpinBox = QtWidgets.QSpinBox(self.new_order)
        self.removerImpresiNSpinBox.setMaximum(999)
        self.removerImpresiNSpinBox.setObjectName("removerImpresiNSpinBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.removerImpresiNSpinBox)
        self.removerSoportesLabel = QtWidgets.QLabel(self.new_order)
        self.removerSoportesLabel.setObjectName("removerSoportesLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.removerSoportesLabel)
        self.spinBox_9 = QtWidgets.QSpinBox(self.new_order)
        self.spinBox_9.setMaximum(999)
        self.spinBox_9.setObjectName("spinBox_9")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_9)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.label_5 = QtWidgets.QLabel(self.new_order)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.textEdit = QtWidgets.QTextEdit(self.new_order)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.gridLayout_8.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.but_return_to_start = QtWidgets.QPushButton(self.new_order)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_return_to_start.sizePolicy().hasHeightForWidth())
        self.but_return_to_start.setSizePolicy(sizePolicy)
        self.but_return_to_start.setMinimumSize(QtCore.QSize(25, 25))
        self.but_return_to_start.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/casa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_return_to_start.setIcon(icon4)
        self.but_return_to_start.setObjectName("but_return_to_start")
        self.gridLayout_8.addWidget(self.but_return_to_start, 0, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem7, 1, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem8, 1, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem9, 1, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.new_order)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_6.setIndent(0)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.dLabel = QtWidgets.QLabel(self.new_order)
        self.dLabel.setObjectName("dLabel")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dLabel)
        self.frabricationCost_label_7 = QtWidgets.QLabel(self.new_order)
        self.frabricationCost_label_7.setObjectName("frabricationCost_label_7")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frabricationCost_label_7)
        self.margenDeBeneficioNetoLabel = QtWidgets.QLabel(self.new_order)
        self.margenDeBeneficioNetoLabel.setObjectName("margenDeBeneficioNetoLabel")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.margenDeBeneficioNetoLabel)
        self.costoDeClienteLabel = QtWidgets.QLabel(self.new_order)
        self.costoDeClienteLabel.setObjectName("costoDeClienteLabel")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.costoDeClienteLabel)
        self.spinBox_8 = QtWidgets.QDoubleSpinBox(self.new_order)
        self.spinBox_8.setSuffix("")
        self.spinBox_8.setMinimum(0.0)
        self.spinBox_8.setMaximum(99999999.0)
        self.spinBox_8.setObjectName("spinBox_8")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_8)
        self.spinBox_7 = QtWidgets.QDoubleSpinBox(self.new_order)
        self.spinBox_7.setMinimum(-100.0)
        self.spinBox_7.setMaximum(9999999.0)
        self.spinBox_7.setProperty("value", 100.0)
        self.spinBox_7.setObjectName("spinBox_7")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_7)
        self.verticalLayout_3.addLayout(self.formLayout_6)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.pushButton_2 = QtWidgets.QPushButton(self.new_order)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.new_order)
        self.edit_inventory = QtWidgets.QWidget()
        self.edit_inventory.setObjectName("edit_inventory")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.edit_inventory)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listWidget_SelectNewItem = QtWidgets.QListWidget(self.edit_inventory)
        self.listWidget_SelectNewItem.setLineWidth(1)
        self.listWidget_SelectNewItem.setObjectName("listWidget_SelectNewItem")
        self.horizontalLayout_5.addWidget(self.listWidget_SelectNewItem)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.edit_inventory)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.blank = QtWidgets.QWidget()
        self.blank.setObjectName("blank")
        self.stackedWidget_2.addWidget(self.blank)
        self.printer = QtWidgets.QWidget()
        self.printer.setObjectName("printer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.printer)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.nameLabel = QtWidgets.QLabel(self.printer)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.printer)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.costoDeUsoLabel = QtWidgets.QLabel(self.printer)
        self.costoDeUsoLabel.setObjectName("costoDeUsoLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.costoDeUsoLabel)
        self.spinBox = QtWidgets.QSpinBox(self.printer)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.gridLayout_3.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.printer)
        self.filament = QtWidgets.QWidget()
        self.filament.setObjectName("filament")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.filament)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.nameLabel_2 = QtWidgets.QLabel(self.filament)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel_2)
        self.nameLineEdit_2 = QtWidgets.QLineEdit(self.filament)
        self.nameLineEdit_2.setObjectName("nameLineEdit_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit_2)
        self.materialLabel_3 = QtWidgets.QLabel(self.filament)
        self.materialLabel_3.setObjectName("materialLabel_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.materialLabel_3)
        self.materialComboBox_3 = QtWidgets.QComboBox(self.filament)
        self.materialComboBox_3.setObjectName("materialComboBox_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.materialComboBox_3)
        self.costoDelCarreteLabel = QtWidgets.QLabel(self.filament)
        self.costoDelCarreteLabel.setObjectName("costoDelCarreteLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.costoDelCarreteLabel)
        self.costoDelCarreteSpinBox = QtWidgets.QSpinBox(self.filament)
        self.costoDelCarreteSpinBox.setObjectName("costoDelCarreteSpinBox")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.costoDelCarreteSpinBox)
        self.gramosDelCarreteLabel = QtWidgets.QLabel(self.filament)
        self.gramosDelCarreteLabel.setObjectName("gramosDelCarreteLabel")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gramosDelCarreteLabel)
        self.spinBox_2 = QtWidgets.QSpinBox(self.filament)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.gramosRestantesLabel = QtWidgets.QLabel(self.filament)
        self.gramosRestantesLabel.setObjectName("gramosRestantesLabel")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gramosRestantesLabel)
        self.spinBox_3 = QtWidgets.QSpinBox(self.filament)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.gridLayout_6.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.filament)
        self.customer = QtWidgets.QWidget()
        self.customer.setObjectName("customer")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.customer)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.nameLabel_3 = QtWidgets.QLabel(self.customer)
        self.nameLabel_3.setObjectName("nameLabel_3")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel_3)
        self.nameLineEdit_3 = QtWidgets.QLineEdit(self.customer)
        self.nameLineEdit_3.setObjectName("nameLineEdit_3")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit_3)
        self.lastNameLabel = QtWidgets.QLabel(self.customer)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lastNameLabel)
        self.lastNameLineEdit = QtWidgets.QLineEdit(self.customer)
        self.lastNameLineEdit.setObjectName("lastNameLineEdit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lastNameLineEdit)
        self.phoneNumberLabel = QtWidgets.QLabel(self.customer)
        self.phoneNumberLabel.setObjectName("phoneNumberLabel")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.phoneNumberLabel)
        self.phoneNumberLineEdit = QtWidgets.QLineEdit(self.customer)
        self.phoneNumberLineEdit.setObjectName("phoneNumberLineEdit")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.phoneNumberLineEdit)
        self.gridLayout_7.addLayout(self.formLayout_5, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.customer)
        self.horizontalLayout_5.addWidget(self.stackedWidget_2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.edit_inventory)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 2, 1, 1)
        self.but_add = QtWidgets.QPushButton(self.edit_inventory)
        self.but_add.setObjectName("but_add")
        self.gridLayout.addWidget(self.but_add, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.but_return_to_start_2 = QtWidgets.QPushButton(self.edit_inventory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_return_to_start_2.sizePolicy().hasHeightForWidth())
        self.but_return_to_start_2.setSizePolicy(sizePolicy)
        self.but_return_to_start_2.setMinimumSize(QtCore.QSize(25, 25))
        self.but_return_to_start_2.setText("")
        self.but_return_to_start_2.setIcon(icon4)
        self.but_return_to_start_2.setObjectName("but_return_to_start_2")
        self.gridLayout_5.addWidget(self.but_return_to_start_2, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem11, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.edit_inventory)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.edit_inventory)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3DPricing"))
        self.label_4.setText(_translate("MainWindow", "Inventario"))
        self.but_add_item.setText(_translate("MainWindow", "Añadir item"))
        self.pushButton_4.setText(_translate("MainWindow", "Eliminar item"))
        self.but_new_order.setText(_translate("MainWindow", "Nueva orden"))
        self.label.setText(_translate("MainWindow", "Crear orden"))
        self.impresoraLabel.setText(_translate("MainWindow", "Impresora"))
        self.materialLabel.setText(_translate("MainWindow", "Material"))
        self.materialLabel_2.setText(_translate("MainWindow", "Tiempo de impresión"))
        self.spinBox_5.setSuffix(_translate("MainWindow", " horas"))
        self.spinBox_4.setSuffix(_translate("MainWindow", " minutos"))
        self.materialWeigthLabel.setText(_translate("MainWindow", "Gramos de material"))
        self.spinBox_6.setSuffix(_translate("MainWindow", " g"))
        self.customerLabel.setText(_translate("MainWindow", "Cliente"))
        self.customers_toolButton.setText(_translate("MainWindow", "..."))
        self.carreteLabel.setText(_translate("MainWindow", "Carrete"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.removerLaImpresiNLabel.setText(_translate("MainWindow", "Preparación (slicing)"))
        self.slicing_time_SpinBox.setSuffix(_translate("MainWindow", " minutos"))
        self.iniciarImpresiNLabel.setText(_translate("MainWindow", "Iniciar impresión"))
        self.iniciarImpresiNSpinBox.setSuffix(_translate("MainWindow", " minutos"))
        self.cambioDeFilamentoYHerramientasLabel.setText(_translate("MainWindow", "Cambio de filamento y herramientas"))
        self.cambioDeFilamentoYHerramientasSpinBox.setSuffix(_translate("MainWindow", " minutos"))
        self.removerImpresiNLabel.setText(_translate("MainWindow", "Remover impresión"))
        self.removerImpresiNSpinBox.setSuffix(_translate("MainWindow", " minutos"))
        self.removerSoportesLabel.setText(_translate("MainWindow", "Remover soportes"))
        self.spinBox_9.setSuffix(_translate("MainWindow", " minutos"))
        self.label_5.setText(_translate("MainWindow", "Descripción de orden:"))
        self.but_return_to_start.setToolTip(_translate("MainWindow", "<html><head/><body><p>Volver al inicio</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Costo"))
        self.dLabel.setText(_translate("MainWindow", "Costo de fabricación"))
        self.frabricationCost_label_7.setText(_translate("MainWindow", "1"))
        self.margenDeBeneficioNetoLabel.setText(_translate("MainWindow", "Margen de beneficio neto"))
        self.costoDeClienteLabel.setText(_translate("MainWindow", "Costo de cliente"))
        self.spinBox_8.setPrefix(_translate("MainWindow", "$ "))
        self.spinBox_7.setSuffix(_translate("MainWindow", " %"))
        self.pushButton_2.setText(_translate("MainWindow", "Agregar orden"))
        self.nameLabel.setText(_translate("MainWindow", "Nombre"))
        self.costoDeUsoLabel.setText(_translate("MainWindow", "Costo de uso"))
        self.spinBox.setSuffix(_translate("MainWindow", " $/hora"))
        self.nameLabel_2.setText(_translate("MainWindow", "Nombre"))
        self.materialLabel_3.setText(_translate("MainWindow", "Material"))
        self.costoDelCarreteLabel.setText(_translate("MainWindow", "Costo del carrete"))
        self.gramosDelCarreteLabel.setText(_translate("MainWindow", "Gramos del carrete"))
        self.gramosRestantesLabel.setText(_translate("MainWindow", "Gramos restantes"))
        self.nameLabel_3.setText(_translate("MainWindow", "Nombre"))
        self.lastNameLabel.setText(_translate("MainWindow", "Apellido"))
        self.phoneNumberLabel.setText(_translate("MainWindow", "Número telefónico"))
        self.pushButton.setText(_translate("MainWindow", "Limpiar campos"))
        self.but_add.setText(_translate("MainWindow", "Añadir"))
        self.but_return_to_start_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Volver al inicio</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Añadir item"))
import resources_rc
